-- La Voie de l'Excellence / Supabase
-- Exécuter dans Supabase SQL Editor.
create extension if not exists pgcrypto;

create type public.user_role as enum ('student','teacher','admin');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Élève',
  avatar_url text,
  role public.user_role not null default 'student',
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  icon text default '📚',
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  subject_id uuid references public.subjects(id) on delete cascade,
  title text not null,
  description text,
  content text,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  subject_id uuid references public.subjects(id) on delete cascade,
  title text not null,
  description text,
  due_at timestamptz,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  file_url text,
  comment text,
  submitted_at timestamptz not null default now(),
  unique(assignment_id, student_id)
);

create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  file_url text not null,
  subject_id uuid references public.subjects(id) on delete set null,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name','Élève'));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.courses enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.resources enable row level security;
alter table public.announcements enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;

create policy "profiles visible to authenticated" on public.profiles for select to authenticated using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());
create policy "subjects visible to authenticated" on public.subjects for select to authenticated using (true);
create policy "courses visible to authenticated" on public.courses for select to authenticated using (true);
create policy "assignments visible to authenticated" on public.assignments for select to authenticated using (true);
create policy "resources visible to authenticated" on public.resources for select to authenticated using (true);
create policy "announcements visible to authenticated" on public.announcements for select to authenticated using (true);
create policy "messages visible to authenticated" on public.messages for select to authenticated using (true);
create policy "users insert messages" on public.messages for insert to authenticated with check (author_id=auth.uid());
create policy "users delete own messages" on public.messages for delete to authenticated using (author_id=auth.uid());
create policy "students read own submissions" on public.submissions for select to authenticated using (student_id=auth.uid());
create policy "students submit own work" on public.submissions for insert to authenticated with check (student_id=auth.uid());
create policy "students update own submission" on public.submissions for update to authenticated using (student_id=auth.uid()) with check (student_id=auth.uid());
create policy "users read own notifications" on public.notifications for select to authenticated using (user_id=auth.uid());
create policy "users update own notifications" on public.notifications for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

insert into public.subjects(name,icon,description) values
('Électronique','⚡','Circuits, composants, mesures'),
('Programmation','💻','Arduino, C/C++, logique'),
('Automatisme','⚙️','Commandes, systèmes, relais'),
('Réseaux','🌐','Communication, IoT, systèmes'),
('Mathématiques','📐','Calculs, formules, applications'),
('Travaux pratiques','🛠️','Projets, laboratoire, défis')
on conflict do nothing;

-- Temps réel pour le chat.
alter table public.messages replica identity full;
alter publication supabase_realtime add table public.messages;
